# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-12 10:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Location', models.CharField(choices=[('Westlands', 'Westlands'), ('Dagoretti', 'Dagoretti'), ('Kibra', 'Kibra'), ('Roysambu', 'Roysambu'), ('Kasarani', 'Kasarani'), ('Ruaraka', 'Ruaraka'), ('Embakasi', 'Embakasi'), ('Madaraka', 'Madaraka'), ('Kamukunji', 'Kamukunji'), ('Starehe', 'Starehe'), ('Mathare', 'Mathare')], max_length=50)),
                ('doctype', models.TextField(choices=[('Pedetritian', 'Family Doctor'), ('Gynecologist', 'Dermatologist'), ('Pyschiatrist', 'Other')], max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('photo_image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Location', models.CharField(choices=[('Westlands', 'Westlands'), ('Dagoretti', 'Dagoretti'), ('Kibra', 'Kibra'), ('Roysambu', 'Roysambu'), ('Kasarani', 'Kasarani'), ('Ruaraka', 'Ruaraka'), ('Embakasi', 'Embakasi'), ('Madaraka', 'Madaraka'), ('Kamukunji', 'Kamukunji'), ('Starehe', 'Starehe'), ('Mathare', 'Mathare')], max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('photo_image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='photos/')),
                ('name', models.CharField(max_length=50)),
                ('medicalId', models.CharField(max_length=10)),
                ('bio', models.TextField(null=True)),
                ('email', models.EmailField(max_length=60, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
